# Generated by Django 2.0 on 2019-04-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0002_auto_20190419_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(default='', help_text='上传的文件', upload_to='message/files/', verbose_name='上传的文件'),
        ),
    ]
