# Generated by Django 2.0 on 2019-04-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='songs.SongsCategory', verbose_name='歌曲类目')),
            ],
            options={
                'verbose_name': '首页歌曲类别广告',
                'verbose_name_plural': '首页歌曲类别广告',
            },
        ),
        migrations.AddField(
            model_name='songs',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='热门推荐'),
        ),
        migrations.AddField(
            model_name='indexad',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='songs.Songs'),
        ),
    ]
