# Generated by Django 2.0 on 2019-04-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20190424_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='cd_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdname', to='cds.CDs', verbose_name='所属专辑'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='singer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singername', to='singers.Singers', verbose_name='歌手'),
        ),
    ]
