# Generated by Django 2.0 on 2019-04-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_id', models.CharField(default='', max_length=50, verbose_name='歌手编号')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='歌手介绍')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='歌手国籍')),
                ('singer_images', models.ImageField(blank=True, null=True, upload_to='singers/images/', verbose_name='歌手照片')),
            ],
            options={
                'verbose_name': '歌手',
                'verbose_name_plural': '歌手',
            },
        ),
    ]
