# Generated by Django 2.0 on 2019-04-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cds',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='热门推荐'),
        ),
    ]
