# Generated by Django 2.0 on 2019-04-29 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0002_cds_is_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cds',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='上传时间', verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='cds',
            name='cd_id',
            field=models.CharField(help_text='专辑编号', max_length=50, verbose_name='专辑编号'),
        ),
        migrations.AlterField(
            model_name='cds',
            name='cds_front_image',
            field=models.ImageField(blank=True, help_text='专辑封面图', null=True, upload_to='cds/images/', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='cds',
            name='is_recommend',
            field=models.BooleanField(default=False, help_text='是否为热门推荐', verbose_name='热门推荐'),
        ),
        migrations.AlterField(
            model_name='cds',
            name='name',
            field=models.CharField(help_text='专辑名', max_length=100, verbose_name='专辑名'),
        ),
    ]
